config/routes.rb
Rails.application.routes.draw do
  resource :home
  resources :accounts

  resources :editors do
    collection do
      get 'search'
    end
  end

  resources :played_games

  resources :parties do

    collection do
      get :all
      get :add_party_form
      get :group
      get :breakdown
      get :most_played
    end

    resources :players
  end

  get "parties/show/:date" => "parties#show", as: "show_parties"
  get "/parties/*date" => "parties#index", as: :parties_resume

  resources :authors, :editions
  resources :authorships do
    collection do
      get :new_partial_form
    end
  end

  resources :account_games, path: "mes-jeux", except: :destroy do
    collection do
      get "recent"  => "account_games#index", kind: "recent", path: "recent"
      get "never_played"  => "account_games#index", kind: "never-played", path: "non-joue"
      get "extensions"  => "account_games#index", kind: "extensions", path: "extensions"
      get "export"
      post :delete_multiple
    end
  end

  resources :members

  resources :tags do
    collection do
      get :lookup
    end
  end

  resources :game_extensions

  resources :games do
    resources :authorships, :editions, :tags

    collection do
      get :search
    end

    member do
      get :replace
      post :merge
    end

    resources :game_extensions do
      collection do
        delete :destroy_multiple
      end
    end
  end

  namespace 'public' do
    resources :libraries, only: :show
  end



  get '/signup' => 'accounts#new', as: :signup
  get '/login'  => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :session
  resource :dashboard

end

app/models/party.rb
# encoding: UTF-8

class InvalidDateRange < Exception; end

class Party < ActiveRecord::Base
  validates :game_id, :account_id, presence: true

  belongs_to :game
  belongs_to :account

  after_create :up_partie_cache, :update_played_date
  after_destroy :down_partie_cache

  scope :for_day, lambda { |date|
    scope = where("parties.created_at BETWEEN ? AND ?", date.beginning_of_day, date.end_of_day)
    scope.order('parties.created_at ASC')
  }


  def self.yearly_breakdown(opts = {})
    options = {
      from: Time.zone.now.year,
      to: Time.zone.now.year,
      scope: {}
    }.merge(opts)

    if options[:game]
      game = options.delete(:game)
      options[:scope] = {
        conditions: { game_id: game.id }
      }
    end
    return ActiveSupport::OrderedHash.new if  options[:from] == nil || options[:to] == nil
    raise InvalidDateRange if options[:from] > options[:to]
    yearly = (options[:from]..options[:to]).inject({}) do |breakdown, year|
      breakdown[year] = (1..12).inject([]) do |acc, month|
        acc << self.by_month(month, year: year).count
      end
      breakdown
    end
    yearly
  end

  def self.breakdown(key)
    joins(:game).group("games.#{key.to_s}").count.inject({}) do |acc, data|
      acc[Game::Target[data[0].to_i][0]] = data[1]
      acc
    end

  end

  def self.player_breakdown(opts = {})
    where(game_id: opts[:game]).group(:nb_player).count(:id)
  end

  def self.play_range(opts = {})
    scope = self
    scope = self.where(game_id: opts[:game]) if opts[:game].present?

    from = if first_played = self.minimum(:created_at)
      first_played.year > 3.year.ago.year ? first_played.year : 3.year.ago.year
    else
      nil
    end
    { from: from, to: Time.zone.now.year }
  end

  def self.previous_play_date_from(date= Time.zone.now)
    where("created_at < ?", date.beginning_of_day).order(created_at: :desc).first
    p.present ? p.created_at  : nil
  end

  def self.next_play_date_from(date= Time.zone.now)
    where("created_at > ?", date.beginning_of_day).order(created_at: :desc).first
    p.present ? p.created_at  : nil
  end

  def self.replace_game(old_game, new_game)
    if new_game && !new_game.new_record?
      where(game_id: game.id).update_all(game_id: old_game.id)
    end
  end


  def self.by_game(game_first_letter = "")
    scope = self.includes(:game).group(:game)
    scope = scope.where("lower(games.name) LIKE ?", "#{game_first_letter}") if game_first_letter.present?
    scope.order('count_id desc').count(:id)
  end


  def self.last_play(count)
    order(created_at: :desc).limit(count)
  end

  def self.most_played(year = Time.zone.now.year, opts = {})
    options = {
      count: 5
    }.reverse_merge(opts)
    scope = self.includes(:game).group(:game)
    if year.to_i > 0
      start_date = (year.to_i - Time.now.year).year.from_now.beginning_of_year
      scope = scope.where("parties.created_at BETWEEN ? AND ?", start_date, start_date.end_of_year)
    end
    scope = scope.limit(options[:count])
    scope.order('count_id desc').count(:id)
  end


  def up_partie_cache
    ac = self.find_account_game
    if ac
      ac.parties_count += 1
      ac.save
    end
  end

  def down_partie_cache
    ac = self.find_account_game
    if ac
      ac.parties_count -= 1
      ac.save
    end
  end

  def update_played_date
    ac = self.find_account_game
    if ac
      ac.last_play = self.created_at
      ac.save
    end
  end


  def find_account_game
    AccountGame.where(game_id: self.game_id, account_id: self.account_id).first
  end

end

app/controllers/parties_controller.rb
# encoding: UTF-8
class PartiesController < ApplicationController
  before_filter :login_required
  subnav :parties

  def index
    @date = params[:date].present? ? Date.strptime(params[:date], '%m/%Y') : Time.zone.now
    @date = @date.to_time
    params[:start_date] = @date
    @prev_date = @date - 1.month - 1.day
    @next_date = @date + 1.month - 1.day
    @parties = current_account.parties.by_month(@date.month, year: @date.year)
    @count = @parties.size
    @days = @parties.group_by{ |p| p.created_at.mday}
    #need to group by game to reduce number of line in calendar
    @days = @days.inject({}) do |acc, parties|
      #partie is an array of all plyed parties for days
      day = parties[0]
      played = parties[1]
      acc[day] = played.group_by{|p| p.game}
      acc
    end
    @games = compute_monthly_played(@parties, @date.beginning_of_month)
    find_yours(@parties)
  end

  def all
    @parties = current_account.parties.by_game(params[:start])
    #always get all played game to compute first letters
    @first_letters = current_account.played_games.first_letters
    @parties = @parties.to_a.paginate(page: params[:page])
    #used to find last played date for each game you've played
    @last_played = current_account.parties.group(:game).maximum(:created_at)
    @last_parties = current_account.parties.last_play(10).group_by(&:game)
    chart_data = current_account.parties.breakdown(:target)
    @chart = Gchart.new( type: :pie,
                         size: '220x220',
                         alt: 'Evolution des parties par mois',
                         legend: chart_data.keys,
                         legend_position: :bottom,
                         data: chart_data.values,
                         theme: :ludomanager)
  end

  def group
    @games = current_account.parties.count(group: 'games.target', include: :game)
    respond_to do |format|
      format.json do
        data = @games.inject([]){ |acc, group| acc << { data: [[1,group[1]]], label: Game::Target[group[0].to_i][0] } }
        render json: data
      end
    end
  end

  def most_played
    @year = params[:year] || nil
    @most_played = current_account.parties.most_played(@year)
    respond_to do |format|
      format.js
    end
  end

  #use in main view ie not in calendar
  def create
    current_account.parties.create(params[:parties].values)
    @date = params[:parties].values.first[:created_at].to_time
    @parties = current_account.parties.by_month(@date.month, year:  @date.year)
    @daily = @parties.select { |p| p.created_at.to_date == @date.to_date }.group_by(&:game)
    @count = @parties.size
    find_yours(@parties)
    @games = compute_monthly_played(@parties,  @date.beginning_of_month)
    respond_to do |format|
      format.js
    end
  end

  def new
    @date = params[:date].to_date
    @form_id = Time.now.to_i
    @index = params[:index] || 1
    @party = Party.new(created_at: @date)
    respond_to do |format|
      format.js
    end
  end

  def add_party_form
    @party = Party.new(created_at: params[:date])
    respond_to do |format|
      format.js
    end
  end

  def show
    @date = params[:date] ? Time.zone.parse(params[:date]) : Time.zone.now
    parties = current_account.parties.by_day(@date) do
      { include: :game }
    end
    @played = {}
    Struct.new('Plays', :players, :plays)
    parties.group_by{|p| p.game}.each do |game, parties|
      @played[game] = parties.group_by { |p| p.nb_player }.inject([]) do |acc, hash|
        acc << Struct::Plays.new(hash[0], hash[1].size)
      end
    end
    @previous = current_account.parties.previous_play_date_from(@date)
    @next = current_account.parties.next_play_date_from(@date)
    @played_before  = current_account.parties.include(:game).before(@date.beginning_of_month).group_by(&:game).keys
    @date = @date.to_date
  end

  def destroy
    @party = current_account.parties.find(params[:id])
    @party.destroy
    respond_to do |format|
      format.js
    end
  end

  protected

  def find_yours(parties)
    account_games = current_account.games
    @other = (parties.map(&:game_id) - (account_games.map(&:id))).size
    @yours = parties.size - @other
  end

  def compute_monthly_played(parties, beginning_of_month)
    played = current_account.parties.group(:game_id).before(beginning_of_month).pluck(:game_id)
    parties.map(&:game).uniq.sort_by{ |game| game.name }.inject([]) do |acc, g|
      acc << [g, !played.include?(g.id), parties.select { |p| p.game_id == g.id }.size ]
    end
  end

  def set_section
    @section = :parties
  end
end

app/helpers/parties_helper.rb
# encoding: UTF-8
module PartiesHelper

  def custom_thead
    ->(dates) {
      Rails.logger.debug dates.inspect
      content_tag(:thead) do
        concat(content_tag(:tr) do
          capture do
            concat content_tag(:th, link_to("Precedent", parties_resume_path(date: [@prev_date.month, @prev_date.year]), class: "left"), colspan: 2)
            concat content_tag(:th, t('date.month_names')[@date.month].humanize, colspan: 3, class: "monthName")
            concat content_tag(:th, link_to("Precedent", parties_resume_path(date: [@prev_date.month, @prev_date.year]), class: "right"), colspan: 2)
          end
        end)
        concat(content_tag(:tr) do
          capture do
            dates.each do |date|
              concat content_tag(:th, t("date.abbr_day_names")[date.wday])
            end
          end
        end)
      end
    }
  end

 def  account_game_status_for(game)
   content_tag(:span, "", class: "ss_sprite ss_flag_green") if account_have_game?(game)
 end

 #display a game nmae according the selected mode used in calendar cell
 # :simple the name is trucated
 # :advanced the name is fully displayed
 #
 def game_name_for(game, parties, mode = :simple)
    name = ""
    if mode == :simple
      name = truncate(game.name, length: parties > 1 ? 9 : 12)
    elsif mode == :advanced
      name = game.name
    end
 end
end

app/views/parties/_calendar_cell.html.erb
<div>
  <%= link_to "jouer", new_party_path(:date => date), :method => :get, :class => "right play" %>
  <div id="day_<%= date.day %>_form" style="z-index:1; position: absolute; display:none; width:auto; height:97px;">

  </div>
  <span class="mday"><%= !parties ?  date.day : link_to(date.day, show_parties_path(date)) %></span>
  <% if parties %>
      <ul class="advanced" id="day_<%= date.day %>_more" style="display: none;">
        <% parties.to_a.each do |game, p| %>
          <%= render :partial => "calendar_party", :locals => {:game => game, :parties => p, :mode => :advanced} %>
        <% end %>
        <li><%= link_to "Less", "#", :class => "less" %></li>
      </ul>
  	<ul class="simple">
  		<% parties.to_a.first(4).each do |game, p| %>
        <%= render :partial => "calendar_party", :locals => {:game => game, :parties => p, :mode => :simple} %>
  		<% end %>
  		<% if  parties.size > 4 %>
  		  <%= content_tag(:li, link_to("#{parties.size - 4} more", "#", :class => "more")) %>
  		<% end %>
  	</ul>
  <% end %>

</div>

app/views/parties/_discovered.html.erb
<% if !@games.empty? %>
  <div class="block">
    <table class="stripe">
      <tbody>
          <% @games.each do |g| %>
            <tr>
              <td class="span-1"><%= image_tag(g[0].box.url(:thumb), :class => "mini") %></td>
              <td>
                <%= link_to g[0].name, game_path(g[0]), :class => "empty" %>
                <%= content_tag(:span,"", :class => "ss_sprite ss_coffee") if g[1] %>
                <%= content_tag(:span, "(x#{g[2]})") if g[2] > 1 %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>		
<% else %>
    <p class="empty">Vous n'avez jouez a aucun jeux ce mois ci.</p>
<% end %>

app/views/parties/_form.html.erb
<li class="party">
  <% fields_for :parties, @party, :index => Time.now.to_i do |p| %>
    <%= text_field_tag "party[game][#{Time.now.to_i}]", nil, :class => "party_game_name", :size => 40 %>
    <div class="auto_complete"></div>
    &nbsp;&agrave;&nbsp;
    <%= p.text_field :nb_player, :size => 2 %>
    <%= p.hidden_field :game_id,  :class => "party_game_id" %>
    <%= p.hidden_field :created_at %>
  <% end %>
</li>

app/views/parties/_last.html.erb
<% if @last_parties.size > 0 %>
  <table>
    <tbody>
      <%= render partial: "parties/last_party", collection: @last_parties %>
    </tbody>
  </table>
<% else %>
  	<p class="empty">Vous n'avez jouez/saisie aucune parties actuellement</p>
<% end %>



app/views/parties/_legend.html.erb
<ul class="horizontal clear">
  <li>
    <div class="legendColorBox left green"><div></div></div>
    Dans ma ludotheque
  </li>
  <li>
    <div class="legendColorBox left orange"><div></div></div>
    Autres
  </li>
</ul>

app/views/parties/_most_played.html.erb
<ul id="top-by-years" class="clear horizontal">
  <% ((Time.now.year - 3)..(Time.now.year)).each do |year| %>
    <li class="<%= "active" if @year.to_s == year.to_s %>">
      <%= link_to year, most_played_parties_path(year: year), :method => :get %>&nbsp;|
    </li>
  <% end %>
  <li class="<%= "active" unless @year %>">
    <%= link_to "Toutes", most_played_parties_path, :method => :get %>
  </li>
</ul>
<% if most_played.any? %>
	<table>
    <tbody>
		<% @most_played.each do |game, count| %>
			<tr>
				<td class="span-1"><%= image_tag(game.box.url(:thumb), :class => "mini") %></td>
				<td>
				  <strong class="empty right">x <%= count %></strong>
				  <%= link_to game.name, game_path(game), :class => "empty" %>
				</td>
			</tr>
		<% end %>
	  </tbody>
  </table>
<% else %>
<p class="empty">Vous n'avez jouez/saisie aucune parties actuellement</p>
<% end%>

app/views/parties/_new.html.erb
<% remote_form_for @party , :html => {:class => "party-form", :id => "party_form_#{@form_id}"} do |f| %>
     <strong>Jeux jou&eacute;(s)</strong><strong class="right">Joueurs</strong>
     <ul id="parties">
       <%= render :partial => "form", :locals  => {:f => f} %>
     </ul>
     <%= link_to_remote("Plus de parties...", {:url => add_party_form_parties_path(:date => @party.created_at.to_date), :method => :get},
                             :class => "ss_sprite ss_add left") %>
     <div class=" clear">
         <div class="right">
             <strong><span class="link reset">Annuler</span> ou <%= submit_tag "Enregistrer" %></strong>
         </div>
     </div>
<% end %>

app/views/parties/_party.html.erb
<tr id="<%= dom_id(game) %>">
	<td class="pad">
	  <%= link_to game.name, played_game_path(game) %>
	</td>
	<td class="align-right">
	  <%= content_tag(:strong,"x #{parties}") %>
    <%= content_tag(:em, "(#{time_ago_in_words(@last_played[game])})", :class => "") if @last_played[game] %>
  </td>
</tr>


app/views/parties/_party_full.html.erb
<tr id="<%= dom_id(party_full) %>" class="autohide">
  <td><%= image_tag(party_full.game.box.url(:thumb), :class => "mini") %></td>
  <td>
    <strong><%= party_full.game.name %></strong><br />
  </td>
  <td><div class="function">
    <% if party_full.players.size > 0 %>
      <%= link_to "", edit_party_player_path(party_full, party_full.players.first),  :class => "ss_sprite ss_pencil"  %>
    <% else %>
      <%= link_to "", new_party_player_path(party_full), :class => "ss_sprite ss_add" %>
    <% end %>
    |<%= link_to_remote "", {:url => party_path(party_full), :method => :delete},  :class => "ss_sprite ss_trash"  %>
  </div></td>
  <td class="center count">
    <div class="<%= party_full.players.size == 0 ? "round empty" : ""  %>">
      <%= party_full.players.size %> / <%= party_full.game.max_player %>
    </div>
  </td>
</tr>

app/views/parties/_subnav.html.erb
<li class="left"><%= link_to "Calendrier", parties_path, :class => "ss_sprite ss_calendar" %></li>
<li class="left"><%= link_to "Vue d'ensemble", all_parties_path, :class => "ss_sprite ss_list" %></li>

app/views/parties/all.html.erb
<h3>Vos parties par jeu</h3>

<% if @parties.size > 0 %>
  <div class="pagination clear">
    <span><%= link_to "Tous", all_parties_path %></span>
      <% ("A".."Z").each do |letter| %>
        <%= link_for_first_letter letter, :all_parties_path %>
      <% end %>
  </div>

  <table class="sortable">
    <thead>
      <tr>
        <th class="span-13">Jeu</th>
        <th class="span-4 align-right last nosort"><strong>x</strong><em>(derniere partie)</em></th>
      </tr>
    </thead>
    <tbody>
      <% @parties.each do |game| %>
        <%= render(:partial => "party", :locals => {:game => game[0], :parties => game[1]}) %>
      <% end %>
    </tbody>
  </table>

  <div class="page-nav">
    <%= will_paginate @parties %>
	</div>
<% else %>
  <p class="empty"> Vous n'avez encore saisie aucune partie.</p>
<% end %>


<% content_for :newsbox do %>
  <div id="placeholder-2">
    <%= render_widget "Repartition de vos parties", :sprite => "ss_pie_chart" do %>
      <%= @chart.image_tag %>
    <% end %>
  </div>

  <div id="placeholder-3">

    <%= render_widget "Vos derniers parties", :sprite => "ss_tower", :partial => "last" %>
  </div>
<% end %>

<% content_for :subnav do %>
	<%= render :partial => "subnav" %>
<% end %>

app/views/parties/breakdown.html.erb
<h3>Mes Jeux > <%= @game.name %></h3>


<div class="column span-17 last">
  <% if @parties.size > 0  %>
  
  <div class="column span-12">
    <p>
      Vous avez jouez <%= pluralize(@parties.size, "partie", "parties") %>
      depuis le <%= l @parties.first.created_at.to_date %>.
       
      Votre derniere parties date du <%= l @parties.last.created_at.to_date %> 
    </p>
  </div>
  <div class="column span-5 last">
    Repartition par anne&eacute:
    <ul>
      <%  @yearly.each do |year, parties| %>
        <li><%= year %> : <%= parties.size %></li>
      <% end %>
    </ul>
  </div>
  
  <div id="breakdown-play" class="column span-17 last">
    <span id="game_id" style="display: none"><%= @game.id %></span>
  </div>
  <% else %>
    <p class="empty">Vous navez encore jamais joue&eacute; a <%= @game.name %></p>
  <% end %>
</div>


<% content_for :newsbox do %>
  <% render_widget "Ils y ont joué" do %>
    <ul class="strip">
      <% @members.each do |p| %>
        <li><%= p.display_name %></li>
      <% end %>
    </ul>
  <% end %>
  
<% end %>

app/views/parties/index.html.erb
<h3>Vos parties de <%=t('date.month_names')[@date.month].humanize %>  <%= @date.year %></h3>


<%= month_calendar start_date: @date, thead: custom_thead, header: -> {}, table: { class: "calendar" }, td: { class: "mday" } do |date| %>
  <% if date.month == @date.month %>
    <%= render "calendar_cell", parties: @days[date.mday], date: date %>
  <% end %>
<% end %>


<% content_for :newsbox do %>
    <div id="placeholder-3">
      <%= render_widget "Les jeux du mois", :sprite => "ss_tower", :partial => 'discovered' %>
    </div>
<% end %>

app/views/parties/show.html.erb
<h3>Vos parties du <%= l @date, :format => :long_ordinal %> </h3>

<% if @played.size > 0 %>

<% @played.each do |game, plays| %>

  <div class="column span-8 game">
    <% unless @played_before.include?(game) %>
      <strong class="right ss_coffee ss_sprite red">new</strong>
    <% end %>
    <h4><%= game.name %></h4>
    <div class="column span-3">
  	  <%= image_tag(game.box.url(:normal), :class => "") %>
    </div>
    <div class="column span-5 last">
      <ul>
        <% plays.each do |p| %>
          <li><%= pluralize(p.plays, "partie", "parties") %> @ <%= pluralize(p.players, "joueur", "joueurs") %>  </li>
        <% end %>
      </ul>
    </div>

  </div>


<% end %>


<% else %>
  <p class="empty">
    Vous n'avez enregistrez aucune partie pour cette date
  </p>

<% end %>

<div class="column pagination span-17 last">
  <%= @previous ? link_to("Precedentes", show_parties_path(@previous.to_date)) : "<span class='disabled'>Precedentes</span>" %>&nbsp;|&nbsp;
  <%= link_to "Retour sur le calendrier", parties_resume_path([@date.month, @date.year]) %>&nbsp;|&nbsp;
  <%= @next ? link_to("Suivantes", show_parties_path(@next.to_date)) : "<span class='disabled'>Suivantes</span>" %>
</div>



<% content_for :newsbox do %>
  <%= render_widget "Mes parties en bref" do %>

  <% end %>
<% end %>

<% content_for :subnav do %>
	<%= render :partial => "subnav" %>
<% end %>