config/routes.rb
Rails.application.routes.draw do
  resource :home
  resources :accounts

  resources :editors do
    collection do
      get 'search'
    end
  end

  resources :played_games

  resources :parties do

    collection do
      get :all
      get :add_party_form
      get :group
      get :breakdown
      get :most_played
    end

    resources :players
  end

  get "parties/show/:date" => "parties#show", as: "show_parties"
  get "/parties/*date" => "parties#index", as: :parties_resume

  resources :authors, :editions
  resources :authorships do
    collection do
      get :new_partial_form
    end
  end

  resources :account_games, path: "mes-jeux", except: :destroy do
    collection do
      get "recent"  => "account_games#index", kind: "recent", path: "recent"
      get "never_played"  => "account_games#index", kind: "never-played", path: "non-joue"
      get "extensions"  => "account_games#index", kind: "extensions", path: "extensions"
      get "export"
      post :delete_multiple
    end
  end

  resources :members

  resources :tags do
    collection do
      get :lookup
    end
  end

  resources :game_extensions

  resources :games do
    resources :authorships, :editions, :tags

    collection do
      get :search
    end

    member do
      get :replace
      post :merge
    end

    resources :game_extensions do
      collection do
        delete :destroy_multiple
      end
    end
  end

  namespace 'public' do
    resources :libraries, only: :show
  end



  get '/signup' => 'accounts#new', as: :signup
  get '/login'  => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :session
  resource :dashboard

end

app/models/edition.rb
# encoding: UTF-8

class Edition < ActiveRecord::Base
  validates :game_id, :editor_id, presence: true
  validates :lang, inclusion: { in: ::Ludomanager::ISOCODES, allow_nil: true, allow_blank: true }

  belongs_to :game
  belongs_to :editor, counter_cache: true

  before_save :set_lang

  scope :for_text, lambda { |q| where('LOWER(name) like ?', "%#{q.downcase}%")}
  scope :latest, lambda { |l| order(created_at: :desc).limit(l) }

  def select_name
    "#{editor.name} - #{lang} - #{published_at.year if published_at}"
  end

  def set_lang
    self.lang  = self.editor.lang if self.lang.blank?
  end


end

app/controllers/editions_controller.rb
# encoding: UTF-8
class EditionsController < ApplicationController
  before_filter :login_required, except: [:index, :show]
  subnav :games

  def index
    if params[:game_id]
      @game = Game.find(params[:game_id])
      @editions = @game.editions.includes(:editor).paginate(page: params[:page])
    else
      @editions = Edition.includes(:game, :editor).order('games.name asc').paginate(page: params[:page])
      @last = Edition.includes(:game, :editor).latest(10)
    end
  end

  def show
    @edition = Edition.find_by_id(params[:id])
  end

  def new
    @game = Game.find(params[:game_id])
    @edition = Edition.new
    @editors = Editor.order(:name)
  end

  def edit
    @game = Game.find_by_id(params[:game_id])
    @edition = @game.editions.find_by_id(params[:id])
    @editors = Editor.order(:name)
  end

  def create
    @game = Game.find_by_id(params[:game_id])
    @edition = @game.editions.build(edition_params)
    if @edition.save
      redirect_to @game, notice: "L'edition a été ajouter a #{@game.name}"
    else
      @editors = Editor.all(order: 'name ASC')
      render action: :new
    end
  end

  def update
    @game = Game.find_by_id(params[:game_id])
    @edition = @game.editions.find_by_id(params[:id])

    if @edition.update_attributes(edition_params)
      redirect_to @game, notice: "Edition mise a jour avec succes"
    else
      render action: :edit
    end
  end

  def destroy
    @game = Game.find_by_id(params[:game_id])
    @edition = @game.editions.find_by_id(params[:id])
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to @game }
      format.js
    end
  end


  protected

  def edition_params
    params.require(:edition).permit(:editor_id, :name, :lang, :published_at)
  end
end

app/helpers/editions_helper.rb
# encoding: UTF-8
module EditionsHelper
end

app/views/editions/_edition.html.erb
<tr class="autohide" id="<%= dom_id(edition) %>">
  <td><span class=" right <%= css_for_lang(edition.lang) %>"></span></td>
  <td><%= link_to edition.name.blank? ? edition.game.name.humanize : edition.name.humanize , game_path(edition.game) %></td>
  <td><%= link_to edition.editor.name, edition.editor %></td>
  <td><%= edition.published_at ? edition.published_at.to_s(:month) : "NA" %></td>
  <td></td>
  <% if logged_in? %>
    <td><div class="function">
      <%= link_to "", edit_game_edition_path(edition.game, edition), :class => "ss_sprite ss_pencil" %>&nbsp;|&nbsp;
      <%= link_to "", edition_path(edition), :method => :delete,  :class => "ss_sprite ss_trash"  %>
    </div></td>
  <% end %>
</tr>

app/views/editions/_form.html.erb
<div class="block">
  <%= form.association  :editor, :collection => @editors, 
                        :label => "Editeur", 
                        :input_html => {:class => "chzn-select" } %>
  <%= form.input  :lang, :collection => Ludomanager::COUNTRIES.collect{ |arr| [arr[0], arr[1]]} %>
  <%= form.input  :published_at, :start_year => 1960, :default => Time.now, 
                  :discard_day => true, :discard_month => true, :label => "Date de parution"  %>
  <%= form.input  :name, :as => :string,
                  :label => "Nom du jeu", :hint => "Seulement si le nom est different de celui de la fiche." %>
</div>

app/views/editions/_list.html.erb
<li class="clear" id="<%= dom_id(list) %>">
  <%= link_to list.editor.name, editor_path(list.editor) %> 
   - <span class="meta"><%= list.name != "" ? list.name : @game.name %></span>
   (<span class="ss_flag <%= css_for_lang(list.lang) %>"></span>) en  
   <span><%= list.published_at.year if list.published_at %></span>
</li>

app/views/editions/_show.html.erb
<% if @editions.size > 0 %>
    <div class="block">
      <h4><span class="ss_sprite ss_joystick">Paru chez :</h4>
      <ul class="strip" id="editions_list">
        <%= render :partial => "editions/list", :collection => @editions %>
      </ul>
    </div>
<% else %>
  <p class="empty">
    Aucune editions n'existe pour le moment
  </p>
<% end %>

app/views/editions/edit.html.erb
<h3>Modification d'un edition de <%= @game.name %></h3>

<%= simple_form_for [@game, @edition]  do |f| %>
  <%= render :partial => f %>
  <%= submit_or_back_to game_editions_path(@game), "retour sur #{@game.name}" %>
<% end %>

app/views/editions/index.html.erb
<% content_for:head do %>
	<title>Les editeurs</title>
<% end %>

<h3>
  <% if @game %>
    Les &eacute;ditions de <%= @game.name %>
  <% else %>
    Gestion des &eacute;ditions
  <% end %>
</h3>


<table class="sortable">
  <thead>
    <tr>
      <th class="span-1">Lang</th>
      <th class="span-9 nosort">Jeux</th>
      <th class="span-3">Editeur</th>
      <th class"span-2">Sortie le</th>
      <th class="span-<%= logged_in? ? "2" : "4" %> nosort"></th>
      <% if logged_in? %>
        <th class="span-2 nosort">Gerer</th>
      <% end %>

    </tr>
  </thead>
  <tbody>
    <%= render :partial => @editions %>
  </tbody>
</table>

<div class="page-nav">
  <%= will_paginate @editions %>
</div>

<% content_for :newsbox do %>
  <%= render_widget "Les dernieres editions", :sprite => "ss_tower" do %>
    <ul class="strip">
      <% @last.each do |edition| %>
        <li>
          <span class=" right <%= css_for_lang(edition.lang) %>"></span>
          <b><%= link_to edition.name.blank? ? edition.game.name : edition.name, edit_game_edition_path(edition.game, edition) %></b>
           chez <span class="empty"><%= edition.editor.name %></span></li>
      <% end %>
    </ul>
  <% end  if @last %>

  <%= render_widget "Adminsitration", :sprite => "ss_tower", :layout => "layouts/game_widget", :locals => {:game => @game} do %>
      <li><%= link_to "Ajouter",  new_game_edition_path(@game), :class => "ss_sprite ss_add" %></li>
      <hr />
      <li><%= link_to "Revenir sur #{@game.name}", game_path(@game), :class => "ss_sprite ss_left" %></li>
  <% end if @game %>
<% end %>

app/views/editions/new.html.erb
<h3>Ajouter une edition de <%= @game.name %></h3>


<%= simple_form_for [@game, @edition]  do |f| %>
  <%= render f %>
  <%= submit_or_back_to game_editions_path(@game), "retour sur #{@game.name}" %>
<% end %>


<% content_for :newsbox do %>
  <%= render_widget "Adminsitration", :sprite => "ss_tower", :layout => "layouts/game_widget", :locals => {:game => @game} do %>
      <li><%= link_to "Supprimer des &eacute;ditions", :class => "ss_sprite ss_trash" %></li>
      <li><%= link_to "Ajouter",  new_game_edition_path(@game), :class => "ss_sprite ss_add" %></li>
      <hr />
      <li><%= link_to "Revenir sur #{@game.name}", game_path(@game), :class => "ss_sprite ss_left" %></li>
  <% end if @game %>
<% end %>

app/views/editions/show.html.erb
<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>