config/routes.rb
Rails.application.routes.draw do
  resource :home
  resources :accounts

  resources :editors do
    collection do
      get 'search'
    end
  end

  resources :played_games

  resources :parties do

    collection do
      get :all
      get :add_party_form
      get :group
      get :breakdown
      get :most_played
    end

    resources :players
  end

  get "parties/show/:date" => "parties#show", as: "show_parties"
  get "/parties/*date" => "parties#index", as: :parties_resume

  resources :authors, :editions
  resources :authorships do
    collection do
      get :new_partial_form
    end
  end

  resources :account_games, path: "mes-jeux", except: :destroy do
    collection do
      get "recent"  => "account_games#index", kind: "recent", path: "recent"
      get "never_played"  => "account_games#index", kind: "never-played", path: "non-joue"
      get "extensions"  => "account_games#index", kind: "extensions", path: "extensions"
      get "export"
      post :delete_multiple
    end
  end

  resources :members

  resources :tags do
    collection do
      get :lookup
    end
  end

  resources :game_extensions

  resources :games do
    resources :authorships, :editions, :tags

    collection do
      get :search
    end

    member do
      get :replace
      post :merge
    end

    resources :game_extensions do
      collection do
        delete :destroy_multiple
      end
    end
  end

  namespace 'public' do
    resources :libraries, only: :show
  end



  get '/signup' => 'accounts#new', as: :signup
  get '/login'  => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :session
  resource :dashboard

end

app/models/account_game.rb
# encoding: UTF-8

class AccountGame < ActiveRecord::Base
  validates :game_id, :account_id, presence: true
  validates :game_id, uniqueness: { scope: :account_id }

  belongs_to :game
  belongs_to :edition
  belongs_to :account

  before_create :setup_default

  scope :recent, -> { where("account_games.transdate > ?", 3.month.ago)}
  scope :no_played, -> { where("parties_count = 0") }
  scope :game_extensions, -> { joins(:game).merge(Game.extensions) }
  scope :base_games, -> { joins(:game).merge(Game.base_games) }


  def self.replace_game(old_game, new_game)
    if new_game && !new_game.new_record?
      update_all("game_id = #{new_game.id}", game_id: old_game.id)
    end
  end

  def self.breakdown(key)
    joins(:game).group("games.#{key.to_s}").count.inject({}) do |acc, data|
      acc[Game::Target[data[0].to_i][0]] = data[1]
      acc
    end
  end


  def recenty_acquired?
    return self.transdate > 3.month.ago
  end

  def played?
    parties_count > 0
  end

  def parties_played_count
    Party.where(game_id: game_id, account_id: account_id).count
  end

  def to_json
    Jbuilder.encode do |json|
      json.extract!(self, :id, :created_at)
      json.game do |g|
        json.extract! game, :id, :name, :min_player, :max_player
        json.extension game.extension?
      end
    end
  end

  protected

  def setup_default
    self.transdate ||= Time.now.to_date
    self.parties_count = self.parties_played_count
  end

end

app/controllers/account_games_controller.rb
# encoding: UTF-8
class AccountGamesController < ApplicationController
  layout "private"
  before_filter :login_required
  subnav :account_games

  def index
    scope = current_account.account_games.includes(:game, edition: :editor)
    scope = scope.order("games.name asc")
    scope = scope.recent if params[:kind] == 'recent'
    scope = scope.no_played if params[:kind] == 'never-played'

    if params[:kind] == 'extensions'
      scope = scope.merge(Game.extensions) if params[:kind] == 'extensions'
      scope = scope.paginate(per_page: params[:per_page], page: params[:page])
      @account_games = @paginated_account_game = scope
    else
      scope = scope.base_games
      scope = scope.paginate(per_page: params[:per_page], page: params[:page])
      @paginated_account_games = scope
      # add extensions right after their base games
      exts = current_account.account_games.game_extensions.where(games: { base_game_id: scope.pluck(:game_id)})
      @account_games = scope.inject([]) do |acc, ac_game|
        acc << ac_game
        loc_ext = exts.select { |ext| ext.game.base_game_id == ac_game.game_id }
        acc += loc_ext unless loc_ext.empty?
        acc
      end
    end
    respond_with(@account_games)
  end

  def export
    @account_games = current_account.games.group_by(&:target)
    respond_to do |format|
      format.csv { render layout: false }
    end
  end


  def new
    @title = t(".page_title")
    @new_games = 4.times.map { current_account.account_games.build }
  end

  def edit
    @account_game = current_account.account_games.find_id(params[:id])
    @editions = Edition.where(game_id: @account_game.game_id).order(:published_at)
  end

  def create
    acc_games = params[:account_games][:account_game].values.select{ |games| games["game_id"] != ""}
    acc_games.each { |ac| ac.delete(:game) }
    @new_games = current_account.account_games.create(acc_games)

    respond_to do |format|
      if @new_games.inject(true) { |acc, record| acc = acc && !record.new_record? }
        @account_games = current_account.account_games
        format.html { redirect_to account_games_url, notice:  "#{@new_games.count} jeux ont été ajoutés a votre ludotheque" }
        format.js do
          @account_game = @new_games.first
        end
      else
        format.html  do
          render action: :new
        end
      end
    end
  end

  def update
    @account_game = current_account.account_games.find_by_id(params[:id])
    #why this line
    params[:account_game] = params[:account_game][@account_game.id.to_s] if params[:account_game].size == 1
    respond_to do |format|
      if @account_game.update_attributes(params[:account_game])
        flash[:notice] = 'AccountGame was successfully created.'
        format.js { render json: @account_game }
        format.html { redirect_to account_games_url }
      else
        format.html { render action: :edit }
      end
    end
  end

  def delete_multiple
    acs = current_account.account_games.where(id: params[:delete_account_games][:ids].split(','))
    acs = acs.destroy_all
    redirect_to account_games_path, notice: "#{acs.size} jeu(x) supprimés de votre ludotheque"
  end

end

app/helpers/account_games_helper.rb
# encoding: UTF-8
module AccountGamesHelper
  def bg_for_status(account_game)
    if !account_game.played?
      "bg-danger"
    elsif account_game.recenty_acquired?
      "bg-success"
    end
  end
  def status_indicator(account_game)
    content_tag(:ul, class:'list-inline') do
      if !account_game.played?
        concat content_tag(:li, content_tag(:span, fa_icon('warning'), class: "btn btn-default btn-circle btn-danger"))
      end
      if account_game.recenty_acquired?
        concat content_tag(:li, content_tag(:span, fa_icon('coffee'), class: "btn btn-default btn-circle btn-success"))
      end
    end
  end

  def parties_indicator(account_game)
    return if account_game.played?
    content_tag(:span, "", class: "ss_sprite ss_error")
  end


  def selectable_tag_list(game)
    tags_li = game.tags.inject(""){|acc, t| acc << content_tag(:li, t.name, class: "#{t.name} tag")}
    content_tag(:ul, tags_li, class: "tags").html_safe
  end
end

app/views/account_games/_account_game.html.slim
= cache account_game do
  = content_tag_for :tr, account_game do
    td
      input(type='checkbox' ng-change="toggleModel(#{account_game.to_json})" ng-model="item#{account_game.id}Status")
    td
      = image_tag(account_game.game.box.url(:normal), size: "70x70", class: "img-thumbnail")
    td(class= "vert-align #{account_game.game.base_game_id.blank? ? '' : "col-md-offset-3"}")
      span.extension-indicator
        - if account_game.game.extension?
          = fa_icon 'link'
      - if account_game.parties_count > 0
        = link_to(account_game.game.name, played_game_path(account_game.game))
      - else
        = account_game.game.name
      - if account_game.game.extension?
        span.text-muted
          |  ( #{account_game.game.base_game.name} )
      | &nbsp;
      = link_to account_game.game, class: "game-preview text-muted", target: "blank", title: "Voir la fiche du jeux", data: { toggle: "tootip", placement: "right"} do
        = fa_icon('eye')
      - if account_game.edition.present?
        .edition.text-muted
          | Parution : #{account_game.edition.editor.name} #{account_game.edition.published_at.year} (#{account_game.edition.lang})


    td= status_indicator account_game
    td De #{account_game.game.min_player} à #{account_game.game.max_player} joueurs
    td= account_game.game.target_str
    td= account_game.game.time_str
    td= account_game.game.difficulty
    td
      - if account_game.parties_count > 0
        span.badge.parties_count(data-toggle="tooltip" title="Joué il y a #{ time_ago_in_words(account_game.last_play) if account_game.last_play}")= account_game.parties_count

app/views/account_games/_form.html.erb
<fieldset>
  <legend>Votre Jeu</legend>
  <% if @editions %>
    <p><%= form.label :edition_id, "Edition" %><br />
    <%= form.collection_select :edition_id, @editions, :id, :select_name %></p>
  <% end %>
  <p><%= form.label :origin, "Origine"  %><br />
  <%= form.text_field :origin, :size => 50 %></p>
  <p><%= form.label :price, "Prix d'achat" %><br />
  <%= form.text_field :price %></p>
  <p><%= form.label :transdate, "Date d'acquisition" %><br />
  <%= form.date_select :transdate %></p>
</fieldset>

app/views/account_games/_last.html.erb
<% if  @last_buyed.size > 0   %>
<table>
  <tbody>
    <%= render :partial => "account_games/last_account_game", :collection => @last_buyed %>
  </tbody>
</table>
<% else %>
  <p class="empty">Vous ne possedez aucun jeux actuellement</p>
<% end %>


app/views/account_games/_last_account_game.html.erb
<tr>
  <td class="span-1"><%= image_tag(last_account_game.game.box.url(:thumb), :class => "mini") %></td>
  <td><strong class="right empty">x <%= last_account_game.parties_count %></strong>
  <%= link_to(last_account_game.game.name, game_path(last_account_game.game), :class => "empty") %><br />
	<span><%= l last_account_game.created_at.to_date %></span></td>
</tr>

app/views/account_games/_search_result.html.erb
<tr>
  <td><%= image_tag(search_result.game.box.url(:thumb), :class => "mini") %></td>
  <td><%= search_result.game.name %></td>
  <td><%= search_result.game.target_str.downcase %></td>
  <td><%= game_tags_links search_result.game %></td>
  <td><%= search_result.game.min_player %>..<%= search_result.game.max_player %></td>
</tr>

app/views/account_games/_search_result_empty.html.erb
<tr>
  <td>&nbsp;</td>
  <td>Aucun de vos jeux correspond a votre recherche.</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>

app/views/account_games/_subnav.html.erb
<li class="left"><%= link_to "Abcdaire", account_games_path, :class => "ss_gamepad ss_sprite" %></li>
<li class="left"><%= link_to "Ajouter un jeu dans votre ludotheque", new_account_game_path, :class => "ss_add ss_sprite" %></li>
<li class="left"><%= link_to "Rechercher", all_account_games_path, :class => "ss_search  ss_sprite" %></li>

app/views/account_games/all.html.erb
<h3>Rechercher un jeu dans ma ludotheque</h3>

<% form_for "search" , :url => search_account_games_path, :method => :post, :html => {:id => "ludo-search", :class => "clear"} do |f| %>
    <div class="column span-19">
        <fieldset>
	        <%= f.label :tag, "Avec le/les tags" %>
      		<%= f.text_field :tags, :size => 80 %>
      		<div class="auto_complete" id="tags_lookup_auto_complete"></div> 
      		<%= f.label :players, "Pour " %>
      		<%= f.text_field :players, :size => 2, :class => "trigger" %> <strong>Joueurs</strong>
          <br />
          Des Categories : <%= f.select :cat1, [["Aucune", -1]] + Game::Target %> ou <%= f.select :cat2, [["Aucune", -1]] + Game::Target %>
    	    <hr />
    	    
    	    <%= f.label :mode,  "Voir les jeux " %>
    	    <%= f.label :mode_all, "Tous" %><%= f.radio_button :mode, :all, :class => "trigger" %> 
    	    <%= f.label :mode_played, "joué" %><%= f.radio_button :mode, :played %> ou
    	    <%= f.label :mode_not_played, "non joué" %><%= f.radio_button :mode, :not_played, :class => "trigger" %>
    	    <%= f.label :mode_not_recent, "Recement ajouté" %><%= f.radio_button :mode, :recent, :class => "trigger" %> 
    	    <div id="time_advanced">
    	      <%= f.label :since, "Depuis" %><%= f.text_field :since, :size => 2, :class => "trigger" %>
    	      <%= f.select :unit, [["Annee", "year"], ["Mois", "month"], ["Jour", "day"]], :class => "trigger" %>
    	    </div>
    	</fieldset>
    </div>
    <div class="column span-4 last clear" id="buttons">
        <%= f.submit "Chercher" %><br />
    	  ou<br />
    	  <%= link_to "Nouvelle recherche", "#", :id => "reset", :class => "ss_textfield_delete ss_sprite" %>
    </div>
<% end %>


<div id="search-results">
    <table>
      <thead>
        <th class="nosort"></th>
        <th class="nosort span-11">Jeux</th>
        <th class="nosort span-2">Cat&eacute;gorie</th>
        <th class="nosort span-10">tags</th>
        <th class="nosort span-1">Joueur</th>
      </thead>
      <tbody id="results">
        <% unless @ag.empty? %>
          <%= render :partial => "search_result", :collection => @ag %>
        <% else %>
          <%= render :partial => "search_result_empty" %>
        <% end %>
      </tbody>
    </table>
</div>



<% content_for :subnav do %>
	<%= render :partial => "subnav" %>
<% end %>

app/views/account_games/edit.html.erb
<h3>Mise a jour de <%= @account_game.game.name %></h3>

<% form_for(@account_game, :url => account_game_path(@account_game), :html => { :method => :put, :id => "account_game_form"}) do |f| %>
  <%= render :partial => f %>
  <%= submit_or_back_to account_games_path, "Retour sur votre ludotheque" %>
<% end %>


<% content_for :subnav do %>
	<%= render :partial => "subnav" %>
<% end %>

app/views/account_games/export.csv.erb
Publique;Nom;Duree;Niveau;Joueur
<% @account_games.each do |target, games| -%>
  <%= "#{Game::Target[target].first} - #{games.size}" %>
  <% games.each do |g| -%>
    ;<%= [g.name, Game::TimeCategory[g.time_category].first, g.difficulty] * ";" %>;<%= (g.min_player..g.max_player).to_a * ";" %>
  <% end %>
<% end %>

app/views/account_games/index.csv.erb
Publique;Nom;Duree;Niveau;Joueur
<% @account_games.each do |target, games| -%>
  <%= "#{Game::Target[target].first} - #{games.size}" %>
  <% games.each do |g| -%>
    ;<%= [g.name, Game::TimeCategory[g.time_category].first, g.difficulty] * ";" %>;<%= (g.min_player..g.max_player).to_a * ";" %>
  <% end %>
<% end %>

app/views/account_games/index.html.slim
- if @account_games.any?

  div(ng-app="AccountGames" ng-controller="AccountGamesController" )
    ul.list-inline
      li.pull-right
        = link_to export_account_games_path(format: :csv) do
          = fa_icon 'file-text-o', class: "btn btn-default btn-circle"
          | &nbsp;Export csv
      li.filter(class="#{"active" if params[:kind].blank? }")
        = link_to pluralize(current_account.account_games.size, "jeu", "jeux"), account_games_path
      li.filter(class="#{"active" if params[:kind] == "extensions"}")
        = link_to  extensions_account_games_path do
          = fa_icon 'link', class: "btn btn-default btn-circle"
          | &nbsp;#{pluralize(current_account.account_games.game_extensions.count , "extension", "extensions")}
      li.filter(class="#{"active" if params[:kind] == "never-played"}")
        = link_to never_played_account_games_path  do
          = fa_icon 'warning', class: "btn btn-default btn-circle btn-danger"
          | &nbsp;#{current_account.account_games.no_played.count} Non Joués
      li.filter(class="#{"active" if params[:kind] == "recent"}")
        = link_to recent_account_games_path  do
          = fa_icon 'coffee', class: "btn btn-default btn-circle btn-success"
          | &nbsp;#{current_account.account_games.recent.count} Recent

    ul.list-inline
      li
        = link_to new_account_game_path, class: "btn btn-primary"
          = fa_icon "plus-circle"
          | Ajouter...
      li
        = link_to '#delete-account-game-modal', "ng-class" => "{disabled: delete_disabled }", class: "btn btn-danger", data: { toggle: "modal" } do
          = fa_icon("trash-o")
          | Supprimer {{selected}}


    table.table.table-hover.listing-with-images
      thead
        tr
          th
          th.col-md-1 Boite
          th(class="col-md-#{@mode == :edit ? 4 : 5 }") Jeux
          th.col-md-1 Statut
          th.col-md-1 Joueurs
          th.col-md-1 Public
          th.col-md-1 Durée
          th.col-md-1 Difficulté
          th Parties
        tbody
          = render @account_games

    = will_paginate @paginated_account_games, renderer: BootstrapPagination::Rails

    = simple_form_for :delete_account_games, url: delete_multiple_account_games_path do |f|
      #delete-account-game-modal.modal.fade
        .modal-dialog
          .modal-content
            .modal-header
              button.close(data-dismiss="modal" aria-hidden="true") &times;
              h4.modal-title Suppression de {{selected}}
            .modal-body
              = f.input_field :ids, as: :hidden, value: "{{selected_ids}}"
              | Etes vous sur de vouloir supprimer {{selected}} de votre ludotheque
            .modal-footer
              button.btn.btn-default(data-dismiss="modal" aria-hidden="true") Annuler
              button.btn.btn-primary Supprimer



- else
  .alert.alert-warning
    strong Attention :
    Vous ne possedez aucun jeux pour le moment.
    = link_to "En ajouter maintenant", new_account_game_path, class: "alert-link"

app/views/account_games/new.html.slim
= simple_form_for "account_games", url: account_games_path, html: { class: "form-horizontal", id: "account-games-form" } do |form|
  - @new_games.each_with_index do |ac, index|
    .row
      = form.fields_for ac, index: index do |f|
        .col-md-6
          = f.input :game, as: :string, input_html: { class: "game-typeahead" }
          = f.input :game_id, as: :hidden, input_html: { class: "game-typeahead-id"}
        .col-md-3
          = f.input :transdate, as: :string, input_html: { class: 'date-time-picker'}
        .col-md-3
          = f.input :edition_id
  = form.submit "Ajouter", class: "btn btn-primary"
  | &nbsp;
  = link_to "Retour a la liste des jeux", :back, class: "btn btn-default"