config/routes.rb
Rails.application.routes.draw do
  resource :home
  resources :accounts

  resources :editors do
    collection do
      get 'search'
    end
  end

  resources :played_games

  resources :parties do

    collection do
      get :all
      get :add_party_form
      get :group
      get :breakdown
      get :most_played
    end

    resources :players
  end

  get "parties/show/:date" => "parties#show", as: "show_parties"
  get "/parties/*date" => "parties#index", as: :parties_resume

  resources :authors, :editions
  resources :authorships do
    collection do
      get :new_partial_form
    end
  end

  resources :account_games, path: "mes-jeux", except: :destroy do
    collection do
      get "recent"  => "account_games#index", kind: "recent", path: "recent"
      get "never_played"  => "account_games#index", kind: "never-played", path: "non-joue"
      get "extensions"  => "account_games#index", kind: "extensions", path: "extensions"
      get "export"
      post :delete_multiple
    end
  end

  resources :members

  resources :tags do
    collection do
      get :lookup
    end
  end

  resources :game_extensions

  resources :games do
    resources :authorships, :editions, :tags

    collection do
      get :search
    end

    member do
      get :replace
      post :merge
    end

    resources :game_extensions do
      collection do
        delete :destroy_multiple
      end
    end
  end

  namespace 'public' do
    resources :libraries, only: :show
  end



  get '/signup' => 'accounts#new', as: :signup
  get '/login'  => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resource :session
  resource :dashboard

end

app/controllers/game_extensions_controller.rb
# encoding: UTF-8
class GameExtensionsController < ApplicationController
  subnav :games

  def index
    if params[:game_id]
      @base = Game.includes(:extensions).find_by_id(params[:game_id])
      @extensions = @base.extensions
    else
      @extensions = Game.extensions
    end
    respond_to do |format|
      format.html
      format.json { render json: @extensions }
    end
  end

  def new
    @base = Game.includes(:extensions).find_by_id(params[:game_id])
    @games = Game.base_games - [@base]
    @extensions = [@base.extensions.build, @base.extensions.build, @base.extensions.build]
  end

  def create
    @base = Game.find_by_id(params[:game_id])
    ids = params[:extensions][:games].values.map{|g| g["id"] }.reject{|id| id.blank?}
    exts = Game.find(ids)
    if(@base && exts.size > 0)
      exts.each do |ext|
        ext.update_attribute(:base_game_id, @base.id)
      end
      respond_to do |wants|
        wants.html { redirect_to(game_path(@base))  }
      end
    else
      respond_to do |wants|
        wants.html do
          @games = Game.all - @base.extensions - [@base]
          @extensions = [@base.extensions.build, @base.extensions.build, @base.extensions.build]
          render :new
        end
      end
    end
  end

  def destroy_multiple
    @base = Game.find_by_id(params[:game_id])
    ids = params[:extensions].values.map{|ext| ext["id"] if ext["delete"] == "1"}.reject{|id| id.blank?}
    exts = Game.find(ids)
    if (exts)
      exts.each do |ext|
        ext.update_attribute :base_game_id, nil
      end
    end

    respond_to do |format|
      format.html { redirect_to(game_game_extensions_path(@base))  }
    end
  end
end

app/helpers/game_extensions_helper.rb
# encoding: UTF-8
module GameExtensionsHelper
end

app/views/game_extensions/_form.html.erb
<div class="block">
  <%= form.collection_select :id, @games, :id, :name, {:prompt => true}, :class => "chzn-select" %>
</div>

app/views/game_extensions/index.html.erb
<% content_for :head  do %>
	<title>Gerer les extensions de <%= @base.name %></title>
<% end %>

<h3>Gerer les extensions de <%= @base.name %>..</h3>

<div class="extensions game">
  <% if @base.extensions.size > 0 %>
    <%= simple_form_for(:extensions, :url => destroy_multiple_game_game_extensions_path(@base),
                      :html => {:method => :delete}) do |f| %>
      <ul class="strip">
        <% @extensions.each_with_index do |extension, index| %>
            <li class="clear">
              <div class="column">
                <%= f.check_box :delete, :index => index %>
                <%= f.hidden_field :id, :index => index, :value => extension.id %>
              </div>
              <div class="column"><%= image_tag extension.box(:thumb), :class => "mini" %></div>
              <div class="line-content span-6 column"><%= link_to(extension.name, game_path(extension)) %></div>
            </li>
        <% end %>
      </ul>
      <div class="buttons clear">
        <div class="right">
          <strong><%= link_to "Retour sur #{@base.name}", game_path(@base) %></strong> ou <%= f.submit "Supprimez les extensions" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="empty">
      <%= @base.name %> n'as aucune extensions pour le moment.
    </p>
  <% end %>
</div>

<% content_for :newsbox do %>
  <%= render_widget "Adminsitration", :sprite => "ss_tower", :layout => "layouts/game_widget", :locals => {:game => @base} do %>
          <li><%= link_to "Supprimer des extensions", game_game_extensions_path(@base), :class => "ss_sprite ss_trash" %></li>
          <li><%= link_to "Ajouter des extensions", new_game_game_extension_path(@base), :class => "ss_sprite ss_add" %></li>
          <hr /></hr>
          <li><%= link_to "Retour sur #{@base.name}", game_path(@base), :class => "ss_sprite ss_document" %></li>
  <% end %>
<% end %>

app/views/game_extensions/new.html.erb
<% content_for :head  do %>
	<title>Ajoutez votre jeu au site</title>
<% end %>

<h3>Ajoutez une/des extension a <%= @base.name %>..</h3>


<%= simple_form_for :extensions, url: game_extensions_path(game_id: @base), html: {:id => "extensions-form"} do |f| -%>
  <%- @extensions.each_with_index do |ext, index| %>
    <%= f.fields_for :games, ext, index: index do |fields| -%>
      <%= render "form",  :form => fields  %>
    <% end -%>
  <% end -%>
  <div class="buttons clear">
    <div class="right">
      <strong><%= link_to "Retour sur #{@base.name}", game_path(@base) %></strong> ou <%= f.submit "Ajoutez les extensions" %>
    </div>
  </div>
<% end -%>

<% content_for :newsbox do %>
  <%= render_widget "Administration", :sprite => "ss_tower" do %>
    <div class="clear">
      <div class="column">
        <%= image_tag(@base.box.url(:normal), :class => "mini left") %>
      </div>
      <div class="column">
        <ul>
          <li><%= link_to "Supprimer des extensions", game_game_extensions_path(@base), :class => "ss_sprite ss_trash" %></li>
          <li><%= link_to "Ajouter des extensions", new_game_game_extension_path(@base), :class => "ss_sprite ss_add" %></li>
          <hr /></hr>
          <li><%= link_to "Retour sur #{@base.name}", game_path(@base), :class => "ss_sprite ss_document" %></li>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>